### PR TITLE
[YUNIKORN-825] The protoc-gen-go version of si.pb.go should be v1.26.…

### PR DESCRIPTION
**Pull request by chia7712**
…0 rather then v1.27.1

### What is this PR for?
the protoc version in go.mod (https://github.com/apache/incubator-yunikorn-scheduler-interface/blob/master/go.mod#L27) is v1.26.0

### What type of PR is it?
* [x] - Bug Fix
* [ ] - Improvement
* [ ] - Feature
* [ ] - Documentation
* [ ] - Hot Fix
* [ ] - Refactoring

### Todos
* [ ] - Task

### What is the Jira issue?
https://issues.apache.org/jira/browse/YUNIKORN-825

### Questions:
* [ ] - The licenses files need update.
* [ ] - There is breaking changes for older versions.
* [ ] - It needs documentation.

### CODE REVIEW

**Comment by wilfred-s** [comment]
This will not fix the issue.

The commit for YUNIKORN-815 is dirty and has incorrect information in the `go.sum` file for the protobuf version.

There is also an issue with the way `go install` works as it was introduced in that change. It automatically upgrades the dependency for the grpc library to the latest version (currently 1.40).
This means that we now have might a moving target. A clean system build will not always build against the same version. Our build system cannot create a reproducible build anymore because the grpc version might just change when running that build.
@yangwwei @kingamarton

**Comment by wilfred-s** [comment]
I have re-opened YUNIKORN-815 to look at the `go install` side of things. For this jira we at least need to remove the two offending lines from `go.sum` so we can proceed with this fix.

**Comment by chia7712** [comment]
> For this jira we at least need to remove the two offending lines from go.sum so we can proceed with this fix.

done. BTW, should we keep `go.mod` and `go.sum` consistent to the result of `go mod tidy`? It is fine to run `go mod tidy` only when making release, but letting them be tidy can avoid unintentional code changes.

**Comment by yangwwei** [comment]
> This will not fix the issue.
> 
> The commit for YUNIKORN-815 is dirty and has incorrect information in the `go.sum` file for the protobuf version.
> 
> There is also an issue with the way `go install` works as it was introduced in that change. It automatically upgrades the dependency for the grpc library to the latest version (currently 1.40).
> This means that we now have might a moving target. A clean system build will not always build against the same version. Our build system cannot create a reproducible build anymore because the grpc version might just change when running that build.
> @yangwwei @kingamarton

Yes, I am working on this ... our SI build is broken, I am unable to update the dep for core and shim because of this. This is failing even before YUNIKORN-815.

**Comment by chia7712** [comment]
it seems #51 can resolve this issue. close this :)

**Pull request closed without merging**
