### PR TITLE
YUNIKORN-488: update protobuf and protoc versions

### PR DESCRIPTION
**Pull request by manirajv06**
### What is this PR for?

To start depends on google.golang.org/protobuf module and protoc (3.14) 

### What type of PR is it?
Improvement

### Todos
* [ ] - Task

### What is the Jira issue?
https://issues.apache.org/jira/browse/YUNIKORN-488

### Questions:
* [ ] - The licenses files need update.
* [ ] - There is breaking changes for older versions.
* [ ] - It needs documentation.

### CODE REVIEW

**Comment by manirajv06** [comment]
@wilfred-s Please take a look at WIP patch. am seeing the below error on running "make" command. Repo path for APIv2 is github.com/protocolbuffers/protobuf-go where as go module path is google.golang.org/protobuf in go.mod. In general, this can be fixed by using "replace" directive. Since above reference is in their repo path, am not sure about the fix. Can you please check?

go: finding module for package github.com/protocolbuffers/protobuf-go/cmd/protoc-gen-go
go: found github.com/protocolbuffers/protobuf-go/cmd/protoc-gen-go in github.com/protocolbuffers/protobuf-go v1.26.0
go: github.com/protocolbuffers/protobuf-go/cmd/protoc-gen-go: github.com/protocolbuffers/protobuf-go@v1.26.0: parsing go.mod:
	module declares its path as: google.golang.org/protobuf
	        but was required as: github.com/protocolbuffers/protobuf-go
make[2]: *** [cmd/protoc-gen-go] Error 1
make[1]: *** [build] Error 2
make: *** [all] Error 2

**Review by wilfred-s — CHANGES_REQUESTED** [review]
For protoc-gen-go: Using the go way would be better than clone and compile from scratch. The hold back on that is  that we are not yet using go 1.16 as the minimum version for the go compiler. Which means we can not use the preferred way i.e. `go install` as we do not have a version support. However we can do a similar trick as we do for the protoc compiler, example:
```
curl -L https://github.com/protocolbuffers/protobuf-go/releases/download/v1.26.0/protoc-gen-go.v1.26.0.darwin.386.tar.gz
```
Unpack and chmod etc into the same bin dir as protoc. Version, OS and arch can be determined in the same way as we do for protoc.
Simpler construct I have used for a separate project.

Also when we do this the go.mod file is brought down to only 2 or 3 lines.

**Review by wilfred-s — CHANGES_REQUESTED** [review]
nits:
* move the PROTOGEN_OS with PROTOC_OS detection
* move PROTOGEN_ARCH with PROTOC_ARCH and add the update `PROTOGEN_ARCH := 386` inside the if for 32 bits machines

Beside those minor changes all is OK

**Review by wilfred-s — APPROVED** [review]
LGTM, committing the change

**Pull request closed without merging**
