### PR TITLE
[YUNIKORN-55] Add pod labels and annotations to allocation ask attributes

### PR DESCRIPTION
**Pull request by adamantal**
Adding constants for `AllocationAsk`

### CODE REVIEW

**Comment by wilfred-s** [comment]
Adding constants in this area does not make sense. None of this is used and is thrown away when the protobuf is generated.

I think we need to remove all of these from the SI and move them to the core code to make them usable. Otherwise we need to come up with a different way of  generating the go file for the constants with the correct paths etc to be included.

Not sure yet what the proper solution is for this.

**Comment by yangwwei** [comment]
Thanks @adamantal , @wilfred-s .  Can we just move these constants to `lib/go/common/constants.go`. We had such discussions before, we need some common library that can be reached from both core and shim, this is the best-fit place. IMO, we don't have to generate everything from protobuf.

**Comment by adamantal** [comment]
I think it's a bit different issue, so I filed [YUNIKORN-135](https://issues.apache.org/jira/browse/YUNIKORN-135) for that issue. After it is committed, I rebase to that, and add my constants to the appropriate package.

**Comment by wilfred-s** [comment]
Based on the discussions we have a new approach under YUNIKORN-135 which has it own #15 

Closing

**Pull request closed without merging**
