### PR TITLE
[YUNIKORN-760] Fix build failures on clean checkout

### PR DESCRIPTION
**Pull request by wilfred-s**
### What is this PR for?
The update of the proto compiler caused the build to fail on a clean
checkout.
The new protoc uses a different plugin setup and stricter rules around
the proto content. gRPC generations has been removed at this point as it
is not used. Simplified the protoc command line.
Make clean and clobber consistentcy changes.

### What type of PR is it?
* [x] - Bug Fix
* [ ] - Improvement
* [ ] - Feature
* [ ] - Documentation
* [ ] - Hot Fix
* [ ] - Refactoring

### What is the Jira issue?
https://issues.apache.org/jira/browse/YUNIKORN-760

### How should this be tested?
Clean checkout of the repo and run make

### Questions:
* [ ] - The licenses files need update.
* [ ] - There is breaking changes for older versions.
* [ ] - It needs documentation.

### CODE REVIEW

**Comment by yangwwei** [comment]
hi @wilfred-s  thanks for fixing this up. Is this a superset of #40?

**Comment by wilfred-s** [comment]
No it is a full replacement of #40. #40 does not fix most of the problems. It allows us to build if you have most of the tools already in your environment. It does just fix a clean build from scratch. Just fixing that one specific issue and leaving all the other problems around is not the right solution.
@updown321  can you please check this too?

**Comment by wilfred-s** [comment]
I seem to have a problem adding @manirajv06 as a reviewer. He should be on the committer list but is not on the committer list in github.

**Review by yangwwei — APPROVED** [review]
Thanks! Approving the changes.

**Pull request merged**
