### PR TITLE
[YUNIKORN-148] add API for queue admin operations

### PR DESCRIPTION
**Pull request by yangwwei**

### CODE REVIEW

**Comment by yangwwei** [comment]
hi @wilfred-s can you help to review the API changes?

**Comment by wilfred-s** [comment]
I see a number of issues with this way of updating:
1) queue type created
If queues are created them as an unmanaged queue the queue will be cleaned up if there are no apps submitted into the queue. If they are a managed queue then the queue config will be out of sync with the memory structure. A next reload of the queues config the update will mark the queue as removed and ready for cleanup. So we are back to the previous case.
2) queue and placement rule interaction
With placement rules active the newly created or deleted queues could change the behaviour of the system without providing traceability. If a rule states "no create" and the queue is not in the system a placement rule would fail, or succeed, after an update. There is no way for an admin to trace this anywhere without going to logs as we do not keep the state anywhere.
3) there is no state kept
Beside the above rule impact we have a generic state issue. This means that there is no way to recover an added queue. Queues for all other cases are either generated when the config is loaded or via placements rules. The newly added queues do not fit in either case which means they are not restored.
4) conflicting update
For the update case if we set a new max on the queue and the queue is already over the max what is the expected behaviour. Are we cancelling the resources over the new limit or do we not take action. The action itself, updating the max resources for instance, might be idempotent the result might not be based on what we implement.

Point 1 and 3 are show stoppers for me at this point.

**Comment by yangwwei** [comment]
I think we should bind this functionality with a certain placement rule.  This is only going to work with unmanaged queues. We are simply changing the behavior of queue creation from the auto-creation to be triggered by namespace events. Nothing else will change. Will this be enough to address above issues?

**Comment by wilfred-s** [comment]
No that doe snot really make it any easier it changes the impact (better and worse) for some of the points:
If we trigger on placement rules only a change in the quota could be delayed by a long time. If there is a change we do not want to wait until somebody submits a new app. Placement rule leverage would help point 1, it will not handle point 3. It will also not handle point 2 if the queue does already exist we do not trigger an update and that would require re-wiring from the placement rules into the scheduler code. This is not there at the moment.

It also still does not solve point 4 and might even make it more difficult.

**Comment by yangwwei** [comment]
Based on the discussion, we will not implement these admin APIs for now. Closing this.

**Pull request closed without merging**
