### PR TITLE
[YUNIKORN-961] Expose build and version information in a REST call

### PR DESCRIPTION
**Pull request by steinsgateted**
### What is this PR for?
in k8shim:
save go build version and build date, and pass to core via scheduler-interface.

in core:
save k8shim's information and the time the scheduler was started.
then the Rest call pushes all information out.

in scheduler-interface:
the message RegisterResourceManagerRequest is extended with the build data.
add a map<string, string> buildInfo = 4 to the message.

### What type of PR is it?
* [ ] - Bug Fix
* [x] - Improvement
* [ ] - Feature
* [ ] - Documentation
* [ ] - Hot Fix
* [ ] - Refactoring

### Todos
* [ ] - Task

### What is the Jira issue?
https://issues.apache.org/jira/projects/YUNIKORN/issues/YUNIKORN-961

### Questions:
* [ ] - The licenses files need update.
* [ ] - There is breaking changes for older versions.
* [ ] - It needs documentation.

### CODE REVIEW

**Comment by steinsgateted** [comment]
It has not been completed, execute make test in k8sshim on the local side, there will be this error:

`fatal error: sync: RUnlock of unlocked RWMutex`

detailed:
```
2022-02-09T00:02:52.602+0800    INFO    entrypoint/entrypoint.go:46     ServiceContext start all services
2022-02-09T00:02:52.606+0800    INFO    entrypoint/entrypoint.go:93     ServiceContext start scheduling services
2022-02-09T00:02:52.607+0800    INFO    entrypoint/entrypoint.go:110    creating InternalMetricsHistory
2022-02-09T00:02:52.607+0800    INFO    entrypoint/entrypoint.go:117    ServiceContext start web application service
2022-02-09T00:02:52.610+0800    INFO    webservice/webservice.go:71     web-app started {"port": 9080}
2022-02-09T00:02:52.610+0800    INFO    log/logger.go:89        scheduler configuration, pretty print   {"configs": "{\n \"schedulerName\": \"yunikorn\",\n \"clusterId\": \"my-kube-cluster\",\n \"clusterVersion\": \"0.1\",\n \"policyGroup\": \"queues\",\n \"schedulingIntervalSecond\": 1000000000,\n \"absoluteKubeConfigFilePath\": \"\",\n \"loggingLevel\": 0,\n \"logEncoding\": \"console\",\n \"logFilePath\": \"\",\n \"volumeBindTimeout\": 10000000000,\n \"testMode\": true,\n \"eventChannelCapacity\": 1048576,\n \"dispatchTimeout\": 300000000000,\n \"kubeQPS\": 1000,\n \"kubeBurst\": 1000,\n \"predicates\": \"\",\n \"operatorPlugins\": \"general,yunikorn-app\",\n \"enableConfigHotRefresh\": false,\n \"disableGangScheduling\": false,\n \"userLabelKey\": \"yunikorn.apache.org/username\"\n}"}
2022-02-09T00:02:52.610+0800    INFO    appmgmt/appmgmt.go:50   Initializing new AppMgmt service
2022-02-09T00:02:52.611+0800    INFO    dispatcher/dispatcher.go:80     Init dispatcher {"EventChannelCapacity": 1048576, "AsyncDispatchLimit": 104857, "DispatchTimeoutInSeconds": 300}
2022-02-09T00:02:52.611+0800    WARN    appmgmt/appmgmt.go:133  App manager is not registered   {"app manager name": "yunikorn-app"}
2022-02-09T00:02:52.611+0800    INFO    dispatcher/dispatcher.go:183    starting the dispatcher
2022-02-09T00:02:52.612+0800    INFO    cache/placeholder_manager.go:144        starting the PlaceholderManager
2022-02-09T00:02:52.612+0800    INFO    shim/scheduler_mock_test.go:119 waiting for scheduler state     {"expected": "Running", "actual": "New"}
fatal error: sync: RUnlock of unlocked RWMutex

goroutine 76 [running]:
```

**Review by wilfred-s — CHANGES_REQUESTED** [review]
The proto file etc are generated from the [md](https://github.com/apache/incubator-yunikorn-scheduler-interface/blob/master/scheduler-interface-spec.md) file in the top level directory.
Instead of adding this into the si.proto you should update the md file (look at line 237 of the md file) and then run `make` in the top level directory of the project also. This should generate the new proto file etc for you.
The update of the message content looks good add a comment to explain what it contains, just the place to add it is not

**Comment by wilfred-s** [comment]
> It has not been completed, execute make test in k8sshim on the local side, there will be this error:
> 
> `fatal error: sync: RUnlock of unlocked RWMutex`

We'll work our way from here through the core to the shim. We'll get the changes committed in that order. Not to worry just yet about those repositories.

**Comment by steinsgateted** [comment]
Modified, and then added a comment:

> // Pass the build information of k8shim to core.
Thanks.

**Comment by steinsgateted** [comment]
> We'll work our way from here through the core to the shim. We'll get the changes committed in that order. Not to worry just yet about those repositories.

I see.Thanks.

**Review by wilfred-s — APPROVED** [review]
+1 LGTM

**Pull request closed without merging**
